/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    parfums: Parfum;
    'familles-olfactives': FamillesOlfactive;
    media: Media;
    articles: Article;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'site-config': SiteConfig;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parfums".
 */
export interface Parfum {
  id: string;
  numeroParf: string;
  inspiration?: string | null;
  genre: 'F' | 'H' | 'U';
  formatParDefaut: '70ml' | '30ml' | '15ml' | '5x15ml';
  familleOlfactive: string | FamillesOlfactive;
  famillePrincipale: string;
  familleSecondaire: string;
  intensite: 'Légère' | 'Moyenne' | 'Forte';
  occasion?: string | null;
  noteTete?: string | null;
  noteCoeur?: string | null;
  noteFond?: string | null;
  description1: string;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  aPropos?: string | null;
  ConseilExpertise?: string | null;
  image?: string | Media | null;
  prix: number;
  variantes?:
    | {
        volume: '70ml' | '30ml' | '15ml' | '5x15ml';
        prix: number;
        ref: string;
        id?: string | null;
      }[]
    | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "familles-olfactives".
 */
export interface FamillesOlfactive {
  id: string;
  nom: string;
  description: {
    [k: string]: unknown;
  }[];
  image?: string | Media | null;
  imagePlaceholder?:
    | ('florale' | 'boisee' | 'orientale' | 'fruitee' | 'aromatique' | 'hesperidee' | 'chypree' | 'fougere')
    | null;
  notesTypiques: string;
  pourQui: string;
  quandPorter: string;
  sousFamilles?:
    | {
        nom: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  evocation: string;
  motParfumeur: string;
  genre: 'masculin' | 'feminin' | 'mixte';
  saison: 'toutes' | 'printemps' | 'ete' | 'automne' | 'hiver' | 'printemps-ete' | 'automne-hiver';
  intensite: 'legere' | 'moderee' | 'intense' | 'tres-intense';
  ordre?: number | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  titre: string;
  slug: string;
  contenu: {
    [k: string]: unknown;
  }[];
  auteur: string;
  datePublication: string;
  imagePrincipale?: string | Media | null;
  imagePlaceholder?: ('blog-parfumerie' | 'conseils-parfums' | 'histoire-parfumerie' | 'tendances') | null;
  resume: string;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  statut: 'brouillon' | 'publie' | 'archive';
  parfumsAssocies?: (string | Parfum)[] | null;
  seo: {
    metaTitre: string;
    metaDescription: string;
    motsCles: string;
  };
  categorieArticle: 'conseils' | 'tendances' | 'histoire' | 'nouveautes' | 'interviews';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: string;
  siteName: string;
  siteDescription: string;
  slogan: string;
  descriptionAccueil?: string | null;
  miseEnAvant: {
    titre: string;
    description: string;
  };
  logoHeader?: string | Media | null;
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}